CREATE TABLE user (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  profile_pic TEXT NOT NULL
);

CREATE TABLE joke (
id INTEGER PRIMARY KEY,
joke TEXT NOT NULL
);

CREATE TABLE motivational (
id INTEGER PRIMARY KEY,
motivational TEXT NOT NULL
);

